# Generated by Django 3.2.19 on 2024-01-13 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'district',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abcapp.district')),
            ],
            options={
                'db_table': 'branch',
            },
        ),
        migrations.CreateModel(
            name='Applicationdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('DOB', models.CharField(max_length=250)),
                ('Age', models.CharField(max_length=250)),
                ('Gender', models.CharField(max_length=250)),
                ('Phone', models.CharField(max_length=250)),
                ('Email', models.CharField(max_length=250)),
                ('Address', models.TextField(max_length=250)),
                ('Account_Type', models.CharField(max_length=250)),
                ('Materials_Provided', models.CharField(max_length=250)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='abcapp.branch')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='abcapp.district')),
            ],
            options={
                'db_table': 'applicationdetails',
            },
        ),
    ]
